language: go
go:
- 1.13.x
env:
  global:
  - secure: PBL+FXIPYrIB06evbPsQwgvk9i7o+c1EW+lxjzTte9jI3xabOCat7BeKldzD6u41SJOwAPmjclSZH+Z2y6fC++8C+v1LVqe9pHrg9VWA/s0CUHrwxysq+xKUbjDpZBAdBqluwfy/sItxV3YBJmhSQFlWCTZ9Zy+h1z9jZNYssbfxYztpYcqUkt4jVXamkt1F68vGbZALiyfC3nz6oWL6grnk7p1psMfT/Es6spJskZquMO5icMevuZ09Djf+6gOT6DPo+5/KCnc/DJ3Q7FDuKfiHzRlvbrO8h4wkzbO+iMHTjVVsjEqTkruR+890ovle9TfWOWtMRLwgHd2Cs9l+1oV8hO4cHnvdlXHT9NW/ilLPr7u6hEaXwWgPievd8N6z0o2rcaOWH6OAgQjs4fMpMcHdIx8INh4gY85oBuST8QzgyUz2uMc0/ruhN3zksXvl3rCUTuQ3quhWbi6+9jZPUWxAYvZl7oe5qTFP5+jXvhQ/0vPzASgwXYjhyZjONRPhntcZQ0fL4oySsyDdYB6UfLL40wZT3j8dSkAwrYrYBIvKz8au/xytZY/cwNlxuUXy9Aj36ncZ+m1MWOziIz2tds8tPEJDSJVPvG5B++ISn8oz5yvrsaI9kYOZFlcczclExSWtd+C3V/L/jLw95bytyMV/XNMugU0B0KwsA7Ops70=
install: true
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PBL+FXIPYrIB06evbPsQwgvk9i7o+c1EW+lxjzTte9jI3xabOCat7BeKldzD6u41SJOwAPmjclSZH+Z2y6fC++8C+v1LVqe9pHrg9VWA/s0CUHrwxysq+xKUbjDpZBAdBqluwfy/sItxV3YBJmhSQFlWCTZ9Zy+h1z9jZNYssbfxYztpYcqUkt4jVXamkt1F68vGbZALiyfC3nz6oWL6grnk7p1psMfT/Es6spJskZquMO5icMevuZ09Djf+6gOT6DPo+5/KCnc/DJ3Q7FDuKfiHzRlvbrO8h4wkzbO+iMHTjVVsjEqTkruR+890ovle9TfWOWtMRLwgHd2Cs9l+1oV8hO4cHnvdlXHT9NW/ilLPr7u6hEaXwWgPievd8N6z0o2rcaOWH6OAgQjs4fMpMcHdIx8INh4gY85oBuST8QzgyUz2uMc0/ruhN3zksXvl3rCUTuQ3quhWbi6+9jZPUWxAYvZl7oe5qTFP5+jXvhQ/0vPzASgwXYjhyZjONRPhntcZQ0fL4oySsyDdYB6UfLL40wZT3j8dSkAwrYrYBIvKz8au/xytZY/cwNlxuUXy9Aj36ncZ+m1MWOziIz2tds8tPEJDSJVPvG5B++ISn8oz5yvrsaI9kYOZFlcczclExSWtd+C3V/L/jLw95bytyMV/XNMugU0B0KwsA7Ops70=
  file_glob: true
  file: dist/*
  on:
    tags: true
  branches:
    only:
    - master
