language: go
go:
- 1.13.x
env:
  global:
    secure: kXT9c9IxvAU1D57XWlQVDLqFSIjRtydAPWi96N+VdWVIIHWuTwCtUjqa1Ws8vq/Db1g3U2IPnVcr4qVE5C1tKqf/66SmUANlXlDwKlSiPwvz1YhlJmdnI3iIkGyI8XLVVcxIBnnqvY4pQ1kTbe6oaAwCqW1nmxrN/jnVfilPDjhDbmWGOrg8fFT2PHeDdKKWiJYUqv2dtrX3XR89wr7senFpWCzmnieojLVVs1COo7TK/NbwVtpsyPHnj+vX9pY62JsOX4Hi11somEU0ay/nuj7yyk42g7bo/Rml3lMzyjpmpEZdmQPqr3Koazp24/vUdCYAzs4mlGS0BiySgj4y4iCvtIdHO0An7+vMv7+NUzyS/Tn3BhyJMgUBOVKLX1FQkLsJgnVr40lUDgD1WN+tK3isHBlBxrpTPPbDqIQ+LgBbgBlu4G16GnYpZtNyFqDPrKzPll/fHSoDuKt39xeqrGkKLbaBuydDaPskXXO3ZjgRWhFWdizomutlpCN+uSgj37HN+IiKnRAwWu/QTHWjotn12jrEQorOfn2dD2IXdUmeMyDotfhwenfFW2GyJ4vZxCBApxfKucVYbLfCJlqMdUsTTS/8VI6/t/z5G2ZDQQEVbd58A0bX1gXS/Jtug/rw3w/A9XR8qAQtSyj2ad7kfxHHeYG1EiJajVEsg5YJTSA=
install: true
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kXT9c9IxvAU1D57XWlQVDLqFSIjRtydAPWi96N+VdWVIIHWuTwCtUjqa1Ws8vq/Db1g3U2IPnVcr4qVE5C1tKqf/66SmUANlXlDwKlSiPwvz1YhlJmdnI3iIkGyI8XLVVcxIBnnqvY4pQ1kTbe6oaAwCqW1nmxrN/jnVfilPDjhDbmWGOrg8fFT2PHeDdKKWiJYUqv2dtrX3XR89wr7senFpWCzmnieojLVVs1COo7TK/NbwVtpsyPHnj+vX9pY62JsOX4Hi11somEU0ay/nuj7yyk42g7bo/Rml3lMzyjpmpEZdmQPqr3Koazp24/vUdCYAzs4mlGS0BiySgj4y4iCvtIdHO0An7+vMv7+NUzyS/Tn3BhyJMgUBOVKLX1FQkLsJgnVr40lUDgD1WN+tK3isHBlBxrpTPPbDqIQ+LgBbgBlu4G16GnYpZtNyFqDPrKzPll/fHSoDuKt39xeqrGkKLbaBuydDaPskXXO3ZjgRWhFWdizomutlpCN+uSgj37HN+IiKnRAwWu/QTHWjotn12jrEQorOfn2dD2IXdUmeMyDotfhwenfFW2GyJ4vZxCBApxfKucVYbLfCJlqMdUsTTS/8VI6/t/z5G2ZDQQEVbd58A0bX1gXS/Jtug/rw3w/A9XR8qAQtSyj2ad7kfxHHeYG1EiJajVEsg5YJTSA=
  file_glob: true
  file: dist/*
  on:
    tags: true
  branches:
    only:
    - master
