language: go
go:
- 1.13.x
env:
  global:
  - secure: NyM2dg0YXFs2voH76qgRIxzxAQmErzk2ozOy8YuCf5LfXYGv/dNHwVetPlSQJTi/RKz7Xg5qeotKGOyHhyVxYinC9fiXdUkJ7SPS8UuUsm+bUxSN7uIPc7dhml65ZDgaOr0Dem5AO9pd6q4D0shNdktdw62FSTozqUTKF15MavjPNQxGUNl1vOwNuxnZ2l2pERoSIIfkgRDwu9sE21g8RvCcC8vs2f8Zr5o8lJKJfpJX66j++QFuu5qa7+Z9nW5cry74kkxy37T4KOLQjvCYEnbkvRnQy7fAejcdNtPlB2rv8tTUA9PshE3UnKHe7lbRDay9Qaa3tjWeqd/q/YK07NhrLygKpJBcuJu1dGv36dOrZeP/sWhrd60MrELi7azDgv8WuGcCP0RqZioQRLEHftLJtXHrebYipo0s0+r6S5glIl/sxmfefovwnmrb3Jvr3/5r1vYmiUbYo5Chc5GyeGj8IJc8jV3iGKXUKYO4q1xg4nY5yPusr88VpiG5gR9Mu/xlEZDhRePF9ox5MXnUyjJdGSbCAFoeV7xx3rYX+eR+TALy37uBZxaCqCJp3rDsflRz5y3Ys3TRcDqZGTgmjqB3KeWM6euk0tZJP/PT2q51Kpp8tdn4HshpKL6oDcW8BjChxv4tZddj7gy+5qjXOK0ikrOC68l20APR/DnBlPc=
install: true
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NyM2dg0YXFs2voH76qgRIxzxAQmErzk2ozOy8YuCf5LfXYGv/dNHwVetPlSQJTi/RKz7Xg5qeotKGOyHhyVxYinC9fiXdUkJ7SPS8UuUsm+bUxSN7uIPc7dhml65ZDgaOr0Dem5AO9pd6q4D0shNdktdw62FSTozqUTKF15MavjPNQxGUNl1vOwNuxnZ2l2pERoSIIfkgRDwu9sE21g8RvCcC8vs2f8Zr5o8lJKJfpJX66j++QFuu5qa7+Z9nW5cry74kkxy37T4KOLQjvCYEnbkvRnQy7fAejcdNtPlB2rv8tTUA9PshE3UnKHe7lbRDay9Qaa3tjWeqd/q/YK07NhrLygKpJBcuJu1dGv36dOrZeP/sWhrd60MrELi7azDgv8WuGcCP0RqZioQRLEHftLJtXHrebYipo0s0+r6S5glIl/sxmfefovwnmrb3Jvr3/5r1vYmiUbYo5Chc5GyeGj8IJc8jV3iGKXUKYO4q1xg4nY5yPusr88VpiG5gR9Mu/xlEZDhRePF9ox5MXnUyjJdGSbCAFoeV7xx3rYX+eR+TALy37uBZxaCqCJp3rDsflRz5y3Ys3TRcDqZGTgmjqB3KeWM6euk0tZJP/PT2q51Kpp8tdn4HshpKL6oDcW8BjChxv4tZddj7gy+5qjXOK0ikrOC68l20APR/DnBlPc=
  file_glob: true
  file: dist/*
  on:
    tags: true
  branches:
    only:
    - master
