language: go
go:
- 1.13.x
env:
  global:
  - secure: WobZqaJe9rSmliwV5hsywwxekejvnlLzW8XtDubE3PvtdXZo8i8Yr1eo0SU/9AmBH0lOF5tNJupnJgXnuc24cKvbbDY2TplPYyT5yy677cjDgU8ZVDH9KIqoX1mYqshGzzOvNRRcVR8n2AcsHBVa+1M+WEa8OEXqlMpA/e+ntXLFMDH/QGCG7yRz08Jik5qp7XjiLKOfoo7PonzxuXN9eXSNbRXIgr5TpXfkDMqIdPnKTgZQHegzNZNxBOBmSW1ReSPEgcnrvJYtrtrB48jDo896cR8s1AgWO8qpaDW1WrOkNXWOrorLbxraX333gAJ7vgLhyBkJEC8sYMLPxbbFXmAZfobP/YerXrPd+zafZ6aE9hfXxHNFllH0DcMr+sh+/hpaveeia/UR+nQfyYKA7W2BYw+AeXcBKI29jfMWpg1DjIKm+Kvhzqg0/sJJtzq4Nkn/yvE/WH478pLVf+TyGdGeZYJatS/ysBFwrI4Ihb1H2pnYxCiWsvQvAlwnkU9bFL6OHe0Y3iROhA0z8uNquZxSGax3AoWdT4lUVFBHx5HLySPPBy/MHe3p7+TG601/IzK/WCnYC/fnhDXb2xEITLahMrUCIqJcYWMpzSdrXblapd5/vUBsk8+GoPnnrhAHL7CZKyh45PuxpLmxb3MbwaXu9OcmQl/xttkIJXzmQnw=
install: true
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: WobZqaJe9rSmliwV5hsywwxekejvnlLzW8XtDubE3PvtdXZo8i8Yr1eo0SU/9AmBH0lOF5tNJupnJgXnuc24cKvbbDY2TplPYyT5yy677cjDgU8ZVDH9KIqoX1mYqshGzzOvNRRcVR8n2AcsHBVa+1M+WEa8OEXqlMpA/e+ntXLFMDH/QGCG7yRz08Jik5qp7XjiLKOfoo7PonzxuXN9eXSNbRXIgr5TpXfkDMqIdPnKTgZQHegzNZNxBOBmSW1ReSPEgcnrvJYtrtrB48jDo896cR8s1AgWO8qpaDW1WrOkNXWOrorLbxraX333gAJ7vgLhyBkJEC8sYMLPxbbFXmAZfobP/YerXrPd+zafZ6aE9hfXxHNFllH0DcMr+sh+/hpaveeia/UR+nQfyYKA7W2BYw+AeXcBKI29jfMWpg1DjIKm+Kvhzqg0/sJJtzq4Nkn/yvE/WH478pLVf+TyGdGeZYJatS/ysBFwrI4Ihb1H2pnYxCiWsvQvAlwnkU9bFL6OHe0Y3iROhA0z8uNquZxSGax3AoWdT4lUVFBHx5HLySPPBy/MHe3p7+TG601/IzK/WCnYC/fnhDXb2xEITLahMrUCIqJcYWMpzSdrXblapd5/vUBsk8+GoPnnrhAHL7CZKyh45PuxpLmxb3MbwaXu9OcmQl/xttkIJXzmQnw=
  file_glob: true
  file: dist/*
  on:
    tags: true
  branches:
    only:
    - master
